branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
    # switch author email to: $(git log -1 --pretty=format:"%aE")
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"
    # repos
    - EMSCRIPTEN_REPOSITORY: "https://github.com/emscripten-core/emsdk.git"
    - VEROVIO_REPOSITORY: "https://${GH_TOKEN}@github.com/rism-ch/verovio"
    # directories
    - CURRENT_PATH: "$(pwd)"
    - EMSCRIPTEN_DIRECTORY: "emsdk"
    - GH_PAGES_DIRECTORY: "gh-pages"
    - OUTPUT_DIRECTORY: "${CURRENT_PATH}/${GH_PAGES_DIRECTORY}"

# cache emscripten installation, tools build and output directory to be used throughout different stages
cache:
  directories:
    - $EMSCRIPTEN_DIRECTORY
    - $GH_PAGES_DIRECTORY
    - tools

# define order of stages
# conditions for any stage can be included here
stages:
  #- build-c++
  - precache
  - build-toolkit
  - deploy

jobs:
  include:
    #################
    # BUILD-C++ STAGE
    #################
    # tests builds on osx and on linux with g++
    #- stage: build-c++
    #  name: osx-xcode
    #  os: osx
    #  osx_image: xcode11.1
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make
    #- name: linux-g++-5
    #  os: linux
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make

    ################
    # PRECACHE STAGE
    ################
    # precaches the emscripten installation, gh-pages, and make-build
    # has to come before "build-toolkit" stage
    - stage: precache
      name: "Precache emscripten installation, make build and gh-pages"
      os: linux
      script:
        - ./ci_precache.sh

    #####################
    # BUILD-TOOLKIT STAGE
    #####################
    # builds toolkit with different options in parallel
    # all "substages" have to use the same id "build-toolkit"
    - stage: build-toolkit-nohumdrum
      name: "no humdrum"
      os: linux
      script:
        - ./ci_build-toolkit.sh nohumdrum
    - stage: build-toolkit-light
      name: "no humdrum light"
      os: linux
      script:
        - ./ci_build-toolkit.sh light
    - stage: build-toolkit-wasm
      name: "no humdrum wasm"
      os: linux
      script:
        - ./ci_build-toolkit.sh wasm
    - stage: build-toolkit-default
      name: "default (with humdrum)"
      os: linux
      script:
        - travis_wait 30 ./ci_build-toolkit.sh default

    ##############
    # DEPLOY stage
    ##############
    # deploys toolkit and doxygen builds
    - stage: deploy
      name: toolkit
      os: linux
      skip_cleanup: true
      script:
        - ./ci_deploy-toolkit.sh
    - name: doxygen
      os: linux
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./ci_deploy-doxygen.sh
