branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"

# cache the emscripten installation in directory "emsdk"
cache:
  directories:
    - emsdk

stages:
  #- build-c++
  - precache-emscripten
  - build-toolkit
  - deploy

jobs:
  include:
    # test build on osx and on linux with g++
    #- stage: build-c++
    #  name: osx-xcode
    #  os: osx
    #  osx_image: xcode11.1
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make
    #- name: linux-g++-5
    #  os: linux
    #  script:
    #    - cd tools
    #    - cmake .
    #    - makec
    # precache the emscripten installation, has to come before "build-toolkit" stage
    - stage: precache-emscripten
      name: "Precache the emscripten installation"
      os: linux
      dist: bionic
      script: true
      before_install:
        - ls -alh  #TODO: remove
        # clone into temporary folder as emsdk folder was created by travis cache before
        # cf. https://stackoverflow.com/a/13852329
        - rm -rf emsdk
        - git clone https://github.com/emscripten-core/emsdk.git
        - ls ./emsdk -alh  # TODO: remove
        - ls ./emsdk/.git -alh  # TODO: remove
      install:
        - cd emsdk
        - ./emsdk install latest
        - cd ..
    # 4 different builds are run in parallel in 4 stages with the same id "build-toolkit"
    - stage: build-toolkit
      name: "no humdrum"
      os: linux
      script:
        - ./emsdk/emsdk activate latest
        - source ./emsdk/emsdk_env.sh
        - ./deploy-develop.sh nohumdrum
    - stage: build-toolkit
      name: "no humdrum light"
      os: linux
      script:
        - ./deploy-develop.sh light
    - stage: build-toolkit
      name: "no humdrum wasm"
      os: linux
      script:
        - ./deploy-develop.sh wasm
    - stage: build-toolkit
      name: "default (with humdrum)"
      os: linux
      script:
        - ./deploy-develop.sh default

    # deploy doxygen build
    - stage: deploy
      name: doxygen
      os: linux
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./deploy-doxygen.sh
