branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"

jobs:
  include:
    # test build on osx and an linux with g++
    - stage: build-c++
      name: osx-xcode
      os: osx
      osx_image: xcode11.1
      script:
        - cd tools
        - cmake .
        - make
    - name: linux-g++-5       
      os: linux
      dist: bionic
      script:
        - cd tools
        - cmake .
        - make
    - stage: build-js
      before_install:
        - git clone https://github.com/emscripten-core/emsdk.git
      install:
        - cd emsdk
        - ./emsdk install latest
        - ./emsdk activate latest
        - source ./emsdk_env.sh
        - cd ..
      script:
        - ./deploy-toolkit-without-humdrum.sh
        - ./deploy-toolkit-without-humdrum-light.sh
        - ./deploy-toolkit-without-humdrum-wasmk.sh
        - ./deploy-toolkit-with-humdrum.sh

    # deploy emscripten build and doxygen
    - stage: deploy
      name: doxygen
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./deploy-doxygen.sh
