branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"
    - VEROVIO_REPOSITORY: "https://${GH_TOKEN}@github.com/rism-ch/verovio"
    - GH_PAGES_DIRECTORY: "gh-pages"
    - CURRENT_PATH: "$(pwd)"
    - OUTPUT_DIRECTORY: "${CURRENT_PATH}/${GH_PAGES_DIRECTORY}"

# cache the emscripten installation and tools build
cache:
  directories:
    - emsdk
    - tools
    - $OUTPUT_DIRECTORY

stages:
  #- build-c++
  - precache-emscripten
  - build-toolkit
  - deploy

jobs:
  include:
    # test build on osx and on linux with g++
    #- stage: build-c++
    #  name: osx-xcode
    #  os: osx
    #  osx_image: xcode11.1
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make
    #- name: linux-g++-5
    #  os: linux
    #  script:
    #    - cd tools
    #    - cmake .
    #    - makec
    # precache the emscripten installation, has to come before "build-toolkit" stage
    - stage: precache-emscripten
      name: "Precache the emscripten installation"
      os: linux
      dist: bionic
      before_install:
        # remove empty emsdk folder created by travis cache before
        - echo "Cloning emscripten"
        - rm -rf emsdk
        - git clone https://github.com/emscripten-core/emsdk.git
      install:
        - cd emsdk
        - ./emsdk install latest
        - cd ..
      before_script:
        # verovio repo
        - echo "Cloning ${VEROVIO_REPOSITORY} into ${GH_PAGES_DIRECTORY}"
        - git clone --single-branch --branch gh-pages ${VEROVIO_REPOSITORY} ${GH_PAGES_DIRECTORY}
      script:
        - cd ./tools
        - cmake .
        - make
        - echo "Update the documentation of the option list"
        - echo "$OUTPUT_DIRECTORY"  # TODO: remove
        - ./verovio -? > $OUTPUT_DIRECTORY/_includes/cli.txt
        - cd ..
    # 4 different builds are run in parallel in 4 stages with the same id "build-toolkit"
    - stage: build-toolkit
      name: "no humdrum"
      os: linux
      script:
        - ./emsdk/emsdk activate latest
        - source ./emsdk/emsdk_env.sh
        - ./deploy-develop.sh nohumdrum
    - stage: build-toolkit
      name: "no humdrum light"
      os: linux
      script:
        - ./deploy-develop.sh light
    - stage: build-toolkit
      name: "no humdrum wasm"
      os: linux
      script:
        - ./deploy-develop.sh wasm
    - stage: build-toolkit
      name: "default (with humdrum)"
      os: linux
      script:
        - ./deploy-develop.sh default

    # deploy doxygen build
    - stage: deploy
      name: doxygen
      os: linux
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./deploy-doxygen.sh
