branches:
  only:
  - develop
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    4

jobs:
  include:
    # test build on osx and an linux with g++
    - stage: build-c++
      name: osx-xcode
      os: osx
      osx_image: xcode11.1
      script:
        - cd tools
        - cmake .
        - make
    - name: linux-g++-5       
      os: linux
      dist: bionic
      script:
        - cd tools
        - cmake .
        - make
    # deploy emscripten build and doxygen
    - stage: deploy
      name: emscripten
      os: linux
      dist: bionic
      env:
        global:
          - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"
      script:
        - git clone https://github.com/emscripten-core/emsdk.git
        - cd emsdk
        - ./emsdk install latest
        - ./emsdk activate latest
        - source ./emsdk_env.sh
        - cd ..
        - ./deploy-develop.sh
    - name: doxygen
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - doxygen
      env:
        global:
          - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"
      script:
        - ./deploy-doxygen.sh
