branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"

stages:
  - build-c++
  - build-emscripten
  - deploy

jobs:
  include:
    # test build on osx and an linux with g++
    - stage: build-c++
      env: # OVERWRITE WITH EMPTY
      name: osx-xcode
    #  os: osx
    #  osx_image: xcode11.1
      script:
        - cd tools
    #    - cmake .
    #    - make
    - name: linux-g++-5
    #  os: linux
    #  dist: bionic
      script:
        - cd tools
    #    - cmake .
    #    - make
    - stage: build-emscripten
      name: "no humdrum"
      env: BUILDTARGET=nohumdrum
      #before_install:
      #  - git clone https://github.com/emscripten-core/emsdk.git
      #install:
      #  - cd emsdk
      #  - ./emsdk install latest
      #  - ./emsdk activate latest
      #  - source ./emsdk_env.sh
      #  - cd ..
      script:
        - ./deploy-test.sh $BUILDTARGET
    - stage: build-emscripten
      name: "no humdrum light"
      env: BUILDTARGET=light
      before_install:
        - git clone https://github.com/emscripten-core/emsdk.git
      install:
      #  - cd emsdk
       # - ./emsdk install latest
       # - ./emsdk activate latest
       # - source ./emsdk_env.sh
       # - cd ..
      script:
        - ./deploy-test.sh $BUILDTARGET


    # deploy doxygen build
    - stage: deploy
      env: # OVERWRITE WITH EMPTY
      name: doxygen
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./deploy-doxygen.sh
