branches:
  only:
  - travis-test
  
sudo: false
dist: bionic
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "lxpugin@gmail.com"
    - VEROVIO_REPOSITORY: "https://${GH_TOKEN}@github.com/rism-ch/verovio"
    - GH_PAGES_DIRECTORY: "gh-pages"
    - CURRENT_PATH: "$(pwd)"
    - OUTPUT_DIRECTORY: "${CURRENT_PATH}/${GH_PAGES_DIRECTORY}"

# cache the emscripten installation and tools build
cache:
  directories:
    - emsdk
    - tools
    - $OUTPUT_DIRECTORY

stages:
  #- build-c++
  - precache
  - build-toolkit
  - deploy

jobs:
  include:
    # test build on osx and on linux with g++
    #- stage: build-c++
    #  name: osx-xcode
    #  os: osx
    #  osx_image: xcode11.1
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make
    #- name: linux-g++-5
    #  os: linux
    #  script:
    #    - cd tools
    #    - cmake .
    #    - make
    # precache the emscripten installation
    # has to come before "build-toolkit" stage
    - stage: precache
      name: "Precache emscripten installation and make build"
      os: linux
      dist: bionic
      before_install:
        # remove empty emsdk folder created by travis cache before
        - echo "Cloning emscripten"
        - rm -rf emsdk
        - git clone https://github.com/emscripten-core/emsdk.git
      install:
        - cd emsdk
        - ./emsdk install latest
        - cd ..
      script:
        - ./ci_precache.sh
    # 4 different builds are run in parallel in 4 stages with the same id "build-toolkit"
    - stage: build-toolkit
      name: "no humdrum"
      os: linux
      script:
        - ./ci_build_toolkit.sh nohumdrum
    - stage: build-toolkit
      name: "no humdrum light"
      os: linux
      script:
        - ./ci_build_toolkit.sh light
    - stage: build-toolkit
      name: "no humdrum wasm"
      os: linux
      script:
        - ./ci_build_toolkit.sh wasm
    - stage: build-toolkit
      name: "default (with humdrum)"
      os: linux
      script:
        - ./ci_build_toolkit.sh default
    - stage: deploy
      name: toolkit
      os: linux
      script:
        - ./ci_deploy-toolkit.sh
    # deploy doxygen build
    - name: doxygen
      os: linux
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./ci_deploy-doxygen.sh
