name: Verovio CI (build JS toolkit)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test

# globals
env:
  # repos
  VEROVIO_REPOSITORY: musicenfanthen/verovio
  EMSCRIPTEN_REPOSITORY: emscripten-core/emsdk
  # branches
  BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
  GH_PAGES_BRANCH: gh-pages
  TEMPORARY_OUTPUT_BRANCH: gh-pages-update-toolkit
  # directories
  CURRENT_PATH: $(pwd)
  EMSCRIPTEN_PATH: emsdk
  GH_PAGES_PATH: gh-pages


jobs:
  # Precache the emscripten installation and make-build for the JS Toolkit Build
  precache:
    name: Precache
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable OUTPUT_PATH
        uses: allenevans/set-env@v1.0.0
        with:
          OUTPUT_PATH: ${{ github.workspace }}/${{ env.GH_PAGES_PATH}}

      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_PATH
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_PATH }}

      - name: Show directory structure
        run: |
          ls -alh
          git status

          echo 'cd gh-pages/_includes'
          echo ${OUTPUT_PATH}
          echo ${OUTPUT_PATH}/_includes
          cd $OUTPUT_PATH/_includes
          ls -alh

      - name: Cache emscripten artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-emscripten
        with:
          path: ${{ env.EMSCRIPTEN_PATH }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('emsdk/emsdk_manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Checkout EMSCRIPTEN_REPOSITORY into EMSCRIPTEN_PATH
        id: emscripten
        uses: actions/checkout@v2
        with:
          repository: ${{ env.EMSCRIPTEN_REPOSITORY }}
          path: ${{ env.EMSCRIPTEN_PATH }}

      - name: Show directory structure
        run: |
          ls -alh

          echo 'cd emsdk'
          cd $EMSCRIPTEN_PATH
          ls -alh

      - name: Install emscripten
        run: |
          echo "Installing emscripten"
          cd $GITHUB_WORKSPACE/$EMSCRIPTEN_PATH
          ./emsdk install latest

      - name: Make build
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake .
          make -j3

          echo "Update the documentation of the option list"
          ./verovio -? > $OUTPUT_PATH/_includes/cli.txt

      - name: Activate and source emscripten tools
        run: |
          cd $GITHUB_WORKSPACE/$EMSCRIPTEN_PATH
          ./emsdk activate latest
          source ./emsdk_env.sh

          cd $GITHUB_WORKSPACE/emscripten
          echo "Building toolkit without humdrum"
          ./buildToolkit -c -H
          cp build/verovio-toolkit.js* $OUTPUT_PATH/javascript/develop/

          echo "Change to Output Directory"
          cd $OUTPUT_PATH/javascript/develop/
          "Show content"
          ls -alh
