name: Verovio CI (build C++)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test

jobs:
  # Build c++ code on different os in parallel
  build_cpp:
    name: Build ${{ matrix.config.os }}-${{ matrix.config.compiler }}-${{ matrix.config.version }}
    # This job runs on all the os specified in strategy.matrix.os
    runs-on: ${{ matrix.config.os }}-latest
    strategy:
      matrix:
        config:
          - os: ubuntu
            compiler: gcc
            version: "6"

          - os: ubuntu
            compiler: gcc
            version: "9"

          - os: ubuntu
            compiler: clang
            version: "6.0"

          - os: ubuntu
            compiler: clang
            version: "9"

#          - os: windows
#            compiler: cl
#            version: "default"
#
#          - os: windows
#            compiler: clang-cl
#            version: "latest"
#
#          - os: windows
#            compiler: clang
#            version: "latest"
#
#          - os: windows
#            compiler: gcc
#            version: "latest"

          - os: macos
            compiler: xcode
            version: "default"

          - os: macos
            compiler: gcc
            version: "latest"

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        id: checkout_main_repo

      - name: Install Ubuntu (${{ matrix.config.compiler }}-${{ matrix.config.version }})
        if: matrix.config.os == 'ubuntu'
        run: |
          curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz -o cmake.tar.gz
          sudo tar xf cmake.tar.gz --strip 1 -C /usr/local
          # LLVM 9 is not yet in Bionic's repositories.
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
          sudo apt-get update
          sudo apt-get install -y ninja-build clang-tidy-9
          sudo ln -s /usr/bin/clang-tidy-9 /usr/local/bin/clang-tidy
          if [ "${{ matrix.config.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.config.version }}
            echo "::set-env name=CC::gcc-${{ matrix.config.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.config.version }}"
          else
            sudo apt-get install -y clang-${{ matrix.config.version }}
            echo "::set-env name=CC::clang-${{ matrix.config.version }}"
            echo "::set-env name=CXX::clang++-${{ matrix.config.version }}"
          fi

      - name: Install macOS (${{ matrix.config.compiler }}-${{ matrix.config.version }})
        if: matrix.config.os == 'macos'
        run: |
          brew install ninja llvm
          sudo ln -s /usr/local/opt/llvm/bin/clang-tidy /usr/local/bin/clang-tidy
          if [ "${{ matrix.config.compiler }}" = "gcc" ]; then
            brew install gcc
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          else
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          fi

      - name: Install Windows (${{ matrix.config.compiler }}-${{ matrix.config.version }})
        if: matrix.config.os == 'windows'
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install ninja llvm --global
          if ("${{ matrix.config.compiler }}" -eq "gcc") {
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          } elseif ("${{ matrix.config.compiler }}" -eq "clang") {
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          } else {
            echo "::set-env name=CC::${{ matrix.config.compiler }}"
            echo "::set-env name=CXX::${{ matrix.config.compiler }}"
          }
          # Make all PATH additions made by scoop and ourselves global.
          echo "::set-env name=PATH::$env:PATH"

      - name: Run make
        id: make
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake .
          make

