name: Verovio CI (build JS toolkit)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test   # TODO: switch back to "develop"

# globals
env:
  # repos
  VEROVIO_REPOSITORY: musicenfanthen/verovio  # TODO: switch back to "rism-ch/verovio"

  # branches
  BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
  GH_PAGES_BRANCH: gh-pages

  # directories
  GH_PAGES_PATH: gh-pages

  # emscripten
  EMSCRIPTEN_PATH: emsdk
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: 'emsdk-cache'


jobs:
  # Precache the emscripten installation and make-build for the JS Toolkit Build
  build_cli:
    name: Build cli
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Create temp dir
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p temp/

      - name: Make build
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake ../cmake
          make -j 8

      - name: Update documentation of the option list
        run: |
          cd $GITHUB_WORKSPACE/tools
          ./verovio -h > $GITHUB_WORKSPACE/temp/cli.txt
          cd $GITHUB_WORKSPACE/temp/
          echo "Show content"
          pwd
          ls -alh

      - name: Upload cli artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli.txt
          path: ${{ github.workspace }}/temp/cli.txt


  build_js:
    name: Build JS toolkit
    # This job runs on linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolkit:
          - option: -c -H -M
            filepath: verovio-toolkit.js*

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Cache emsdk artifacts
        id: cache-emsdk
        uses: actions/cache@v2
        with:
          # path for cache
          path: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}
          # key for cache
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}

      - name: Verify emscripten build
        run: emcc -v

      - name: Create temp dir
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p temp

      - name: Build Toolkit
        run: |
          cd $GITHUB_WORKSPACE/emscripten
          echo "Building toolkit without humdrum"
          ./buildToolkit ${{ matrix.toolkit.option }}
          cp build/${{ matrix.toolkit.filepath }} $GITHUB_WORKSPACE/temp/
          cd $GITHUB_WORKSPACE/temp/
          echo "Show content"
          pwd
          ls -alh

      - name: Upload js build artifact
        uses: actions/upload-artifact@v2
        with:
          name: verovio-toolkit.js
          path: ${{ github.workspace }}/temp/${{ matrix.toolkit.filepath }}

      - name: List all files
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/temp/
          pwd
          ls -al
          git status

  deploy:
    name: Deploy
    # This job runs on linux
    runs-on: ubuntu-latest
    needs: build_js
    steps:
      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_PATH
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_PATH }}

      - name: Download build artifacts
        uses: actions/download-artifact@v2

      - name: Verify
        run: |
          ls -R
