name: Verovio CI (build JS toolkit)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test   # TODO: switch back to "develop"

# globals
env:
  # repos
  VEROVIO_REPOSITORY: musicenfanthen/verovio  # TODO: switch back to "rism-ch/verovio"

  # branches
  BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
  GH_PAGES_BRANCH: gh-pages

  # directories
  GH_PAGES_PATH: gh-pages

  # emscripten
  EMSCRIPTEN_PATH: emsdk
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: 'emsdk-cache'


jobs:
  # Precache the emscripten installation and make-build for the JS Toolkit Build
  precache:
    name: Precache
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable OUTPUT_PATH
        uses: allenevans/set-env@v1.0.0
        with:
          overwrite: false
          OUTPUT_PATH: ${{ github.workspace }}/${{ env.GH_PAGES_PATH}}

      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Cache output artifacts
        id: cache-output-path
        uses: actions/cache@v2
        with:
          # path for cache
          path: ${{ env.OUTPUT_PATH }}
          # key for cache
          key: ${{ runner.os }}-output-${{ github.sha }}

      - name: Verify
        run: |
          echo ${OUTPUT_PATH}

      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_PATH
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_PATH }}

      - name: Cache emsdk artifacts
        uses: actions/cache@v2
        id: cache-emsdk
        with:
          # path for cache
          path: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}
          # key for cache
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: ${{ env.EMSCRIPTEN_CACHE_FOLDER }}


      - name: Verify
        run: emcc -v

      - name: Make build
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake ../cmake
          make -j 8

      - name: Update documentation of the option list
        run: |
          echo "./verovio -h > $OUTPUT_PATH/_includes/cli.txt"
          cd $GITHUB_WORKSPACE/tools
          ./verovio -h; echo $?
          ./verovio -h > $OUTPUT_PATH/_includes/cli.txt; echo $?

      - name: Upload cli artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli.txt
          path: $OUTPUT_PATH/_includes/cli.txt

      - name: Build Toolkit
        run: |
          cd $GITHUB_WORKSPACE/emscripten
          echo "Building toolkit without humdrum"
          ./buildToolkit -c -H
          cp build/verovio-toolkit.js* $OUTPUT_PATH/javascript/develop/

      - name: Upload js build artifact
        uses: actions/upload-artifact@v2
        with:
          name: verovio-toolkit.js
          path: $GITHUB_WORKSPACE/emscripten/build/verovio-toolkit.js*


      - name: Verify
        run: |
          echo "Change to Output Directory"
          cd $OUTPUT_PATH/javascript/develop/
          echo "Show content"
          pwd
          ls -alh
          git status

      - name: List all files
        if: always()
        run: |
          cd $OUTPUT_PATH
          pwd
          ls -al
          git status
