name: Verovio CI (build JS toolkit)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test   # TODO: switch back to "develop"

# globals
env:
  # repos
  VEROVIO_REPOSITORY: musicenfanthen/verovio  # TODO: switch back to "rism-ch/verovio"
  EMSCRIPTEN_REPOSITORY: emscripten-core/emsdk

  # branches
  BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
  GH_PAGES_BRANCH: gh-pages

  # directories
  EMSCRIPTEN_PATH: emsdk
  GH_PAGES_PATH: gh-pages

  # others
  EMSCRIPTEN_VERSION: 1.39.6


jobs:
  # Precache the emscripten installation and make-build for the JS Toolkit Build
  precache:
    name: Precache
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable OUTPUT_PATH
        uses: allenevans/set-env@v1.0.0
        with:
          OUTPUT_PATH: ${{ github.workspace }}/${{ env.GH_PAGES_PATH}}

      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Cache output artifacts
        uses: actions/cache@v1
        id: cache-output-path
        with:
          # path for cache
          path: ${{ env.OUTPUT_PATH }}
          # key for cache
          key: ${{ runner.os }}-output-${{ github.sha }}

      - name: Verify
        run: |
          echo ${OUTPUT_PATH}

      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_PATH
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_PATH }}

      - name: Cache emsdk artifacts
        uses: actions/cache@v1
        id: cache-emsdk
        with:
          # path for cache
          path: ${{ env.EMSCRIPTEN_PATH }}
          # key for cache
          key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}

      - name: Setup emsdk (use cache if found, create otherwise)
        uses: mymindstorm/setup-emsdk@v2
        with:
          # Make sure to set a version number!
          version: ${{ env.EMSCRIPTEN_VERSION }}
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: ${{ env.EMSCRIPTEN_PATH }}
          # This stops it from using tc.cacheDir since we are using
          #  actions/cache.
          no-cache: true

      - name: Verify
        run: emcc -v

      - name: Make build
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake .
          make -j3

          echo "Update the documentation of the option list"
          ./verovio -? > $OUTPUT_PATH/_includes/cli.txt

      - name: Build Toolkit
        run: |
          cd $GITHUB_WORKSPACE/emscripten
          echo "Building toolkit without humdrum"
          ./buildToolkit -c -H
          cp build/verovio-toolkit.js* $OUTPUT_PATH/javascript/develop/

      - name: Verify
        run: |
          echo "Change to Output Directory"
          cd $OUTPUT_PATH/javascript/develop/
          echo "Show content"
          ls -alh
          git status
