name: Verovio CI (test suite)

on:
  # Trigger the workflow on push,
  # but only for the travis-test branch
  push:
    branches:
      - travis-test   # TODO: switch back to "develop"

# globals
env:
  # repos
  VEROVIO_REPOSITORY: musicenfanthen/verovio  # TODO: switch back to "rism-ch/verovio"

  # branches
  BUILD_BRANCH: travis-test   # TODO: switch back to "develop"
  GH_PAGES_BRANCH: gh-pages

  # directories
  GH_PAGES_PATH: gh-pages

  # emscripten
  EMSCRIPTEN_PATH: emsdk
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: 'emsdk-cache'


jobs:
  run_tests:
    name: Run tests
    # This job runs on linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

